environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Toy Doc Search
python_version: py311
requirements:
  - torch==2.0.1
  - sentence-transformers==3.0.0
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
